<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User Name_ctl00MainContenttxtUserName</name>
   <tag></tag>
   <elementGuidId>50dcffe9-83e3-471d-808a-c153dedbde06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_MainContent_txtUserName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_txtUserName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ctl00_MainContent_txtUserName</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e6641cd-8be6-4622-8f81-09ae4d5fac66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$txtUserName</value>
      <webElementGuid>9ed600b7-d4c6-415b-ab47-90f3021cacf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>35364642-07a2-4007-8984-5835303833c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_txtUserName</value>
      <webElementGuid>24f4b611-31f3-4000-8f29-a178fad0d278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loginInput</value>
      <webElementGuid>8a2c73ab-a99f-4621-9820-651a6a1626d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_txtUserName&quot;)</value>
      <webElementGuid>cbdc4397-e286-43f6-a7a9-9c882a4ed945</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_MainContent_txtUserName']</value>
      <webElementGuid>70f74201-04f6-4fa4-92a6-d5bcb571c6aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/div[3]/article/div/input</value>
      <webElementGuid>8ed77675-5cf7-475c-9302-7447a805e8d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div/input</value>
      <webElementGuid>699d2b51-780e-424d-9afd-3fbece67692f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$MainContent$txtUserName' and @type = 'text' and @id = 'ctl00_MainContent_txtUserName']</value>
      <webElementGuid>30132ffe-b18e-4093-a564-6f7d688583ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
