<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Check in</name>
   <tag></tag>
   <elementGuidId>35aa7cd5-0130-4ab9-b156-79afd41a39bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.lk4ruxu.atm_c8_1uc0753.atm_g3_lonqig.atm_cs_10d11i2.atm_fr_idpfg4.atm_le_yh40bf.dir.dir-ltr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search-tabpanel']/div/div[3]/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;structured-search-input-field-split-dates-0&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d56a2c98-673e-4e76-80ca-10b00f8b2d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lk4ruxu atm_c8_1uc0753 atm_g3_lonqig atm_cs_10d11i2 atm_fr_idpfg4 atm_le_yh40bf dir dir-ltr</value>
      <webElementGuid>d9540109-e88b-4254-9a1a-d715958ebd00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Check in</value>
      <webElementGuid>0793c98f-a1cd-4662-8a6b-898405dde21f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-tabpanel&quot;)/div[@class=&quot;ir2ixub atm_9s_1txwivl atm_h_1h6ojuz atm_am_163v1yp atm_e2_1osqo2v atm_jb_idpfg4 atm_mj_1wugsn5 dir dir-ltr&quot;]/div[@class=&quot;cwk1mic atm_9s_1txwivl atm_am_eqk4pz atm_jb_idpfg4 dir dir-ltr&quot;]/div[@class=&quot;c1ddhymz atm_am_16wc86f atm_h_1h6ojuz atm_9s_1txwivl atm_gi_1n1ank9 atm_jb_idpfg4 atm_mk_h2mmj6 atm_vy_10bmcub dir dir-ltr&quot;]/div[@class=&quot;b1spesa7 atm_1s_glywfm atm_26_1j28jx2 atm_3f_idpfg4 atm_7l_1kw7nm4 atm_9j_tlke0l atm_bx_1kw7nm4 atm_c8_1kw7nm4 atm_cs_1kw7nm4 atm_g3_1kw7nm4 atm_gi_idpfg4 atm_ks_ewfl5b atm_rd_glywfm atm_vb_1wugsn5 atm_kd_glywfm atm_9s_1ulexfb atm_am_qk3dho atm_l8_t94yts atm_r3_1e5hqsa atm_vy_idpfg4 atm_wq_kb7nvz atm_3f_glywfm_jo46a5 atm_l8_idpfg4_jo46a5 atm_gi_idpfg4_jo46a5 atm_3f_glywfm_1icshfk atm_kd_glywfm_19774hq atm_6h_1s2714j_vmtskl atm_66_nqa18y_vmtskl atm_4b_1egtlkw_vmtskl atm_92_1yyfdc7_vmtskl atm_9s_glywfm_vmtskl atm_e2_1vi7ecw_vmtskl atm_fq_idpfg4_vmtskl atm_h3_4h84z3_vmtskl atm_mk_stnw88_vmtskl atm_n3_idpfg4_vmtskl atm_tk_1ssbidh_vmtskl atm_wq_idpfg4_vmtskl atm_2a_1u8qnfj_9in345 atm_3f_okh77k_9in345 atm_5j_1vi7ecw_9in345 atm_6i_idpfg4_9in345 atm_92_1yyfdc7_9in345 atm_fq_idpfg4_9in345 atm_mk_stnw88_9in345 atm_n3_idpfg4_9in345 atm_tk_idpfg4_9in345 atm_wq_idpfg4_9in345 b1fbhdca atm_gi_eflcwz_9bj8xt atm_2d_um1unu_9bj8xt atm_wq_cs5v99_1w3cfyq atm_9s_1ulexfb_9xuho3 atm_uc_aaiy6o_1tasb51 atm_4b_dezgoh_1tasb51 atm_70_1t2bbnk_1tasb51 atm_gi_eflcwz_1tasb51 atm_uc_glywfm_1tasb51_1rrf6b5 atm_wq_cs5v99_pfnrn2_1oszvuo atm_9s_1ulexfb_1buez3b_1oszvuo atm_uc_aaiy6o_1fu4lp4_1oszvuo atm_4b_dezgoh_1fu4lp4_1oszvuo atm_70_1t2bbnk_1fu4lp4_1oszvuo atm_gi_eflcwz_1fu4lp4_1oszvuo atm_uc_glywfm_1fu4lp4_1o31aam b1sse431 atm_92_1yyfdc7_1rqz0hn atm_9s_1ulexfb_1rqz0hn atm_vy_1yysq1q_1rqz0hn atm_e2_1huphc_1rqz0hn atm_mk_stnw88_1rqz0hn atm_h3_idpfg4_1rqz0hn atm_fq_kgzxrn_1rqz0hn atm_tk_t94yts_1rqz0hn atm_wq_idpfg4_1rqz0hn atm_26_1rxyd3j_1rqz0hn dir dir-ltr&quot;]/div[@class=&quot;cz9siyu atm_l8_srw7uq atm_ks_15vqwwr atm_mk_h2mmj6 atm_vv_1q9ccgz atm_vy_1osqo2v atm_wq_kb7nvz dir dir-ltr&quot;]/div[@class=&quot;lk4ruxu atm_c8_1uc0753 atm_g3_lonqig atm_cs_10d11i2 atm_fr_idpfg4 atm_le_yh40bf dir dir-ltr&quot;]</value>
      <webElementGuid>b45e3013-a0f1-4949-b8dd-873618de6607</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-tabpanel']/div/div[3]/div/div/div/div</value>
      <webElementGuid>a564a573-daaa-4da0-97ee-09f9305e3ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Greece'])[1]/following::div[6]</value>
      <webElementGuid>69c87a9f-a5b2-4cea-8f70-2cf8d3ccd600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Europe Square, Tbilisi, Georgia'])[1]/following::div[10]</value>
      <webElementGuid>fc0fb09e-0bc5-4fcc-b664-d2c1a917542f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add dates'])[1]/preceding::div[1]</value>
      <webElementGuid>2fc84a94-3e56-4c02-9f85-d775ece1dc7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check out'])[1]/preceding::div[3]</value>
      <webElementGuid>55dbed88-b432-4ab9-b457-ed9ffa254e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Check in']/parent::*</value>
      <webElementGuid>0be52c71-d544-46c4-8c32-c472b00b519e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/div/div/div</value>
      <webElementGuid>14093d63-02d8-4009-94f7-785525b1c995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Check in' or . = 'Check in')]</value>
      <webElementGuid>ff63b6e4-b13c-4130-a2ae-677f644c3b91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
