<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_9</name>
   <tag></tag>
   <elementGuidId>cde19ec7-e21a-4d86-b2fc-969bf024e062</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.c1i3jwjb.atm_gz_t94yts.atm_h0_t94yts.c1buxrsh.atm_c8_km0zk7.atm_g3_18khvle.atm_fr_1m9t47k.atm_9s_1txwivl.atm_h_1h6ojuz.atm_fc_1h6ojuz.atm_ar_1bp4okc.atm_5j_1osqo2v.atm_mk_h2mmj6.atm_cs_10d11i2.d1qdcyln.atm_7l_dezgoh.atm_3f_nneixv.n1h9hfmv.atm_26_1p8m8iw_1nos8r.atm_3f_1vpejwz_1nos8r.dir.dir-ltr.notranslate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel--tabs--0']/div/div/div/div/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[2]/td[6]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;9, Friday, August 2024, Today. Available. Select as check-in date.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cf5f3c3c-2623-4279-aaeb-325315754ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c1i3jwjb atm_gz_t94yts atm_h0_t94yts c1buxrsh atm_c8_km0zk7 atm_g3_18khvle atm_fr_1m9t47k atm_9s_1txwivl atm_h_1h6ojuz atm_fc_1h6ojuz atm_ar_1bp4okc atm_5j_1osqo2v atm_mk_h2mmj6 atm_cs_10d11i2 d1qdcyln atm_7l_dezgoh atm_3f_nneixv n1h9hfmv atm_26_1p8m8iw_1nos8r atm_3f_1vpejwz_1nos8r dir dir-ltr notranslate</value>
      <webElementGuid>e11182bc-e0fa-4e80-9d5d-5bd58f4127dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>09/08/2024</value>
      <webElementGuid>017c5b26-edbc-41d9-888a-1b186a2e8663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-is-day-blocked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a92b88a3-fba4-4a21-9234-38d05205e5a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>b987d133-c9e9-49cb-a06f-7f5e683a6928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel--tabs--0&quot;)/div[@class=&quot;dioea41 atm_h_1h6ojuz__7pk1ck atm_9s_1txwivl__7pk1ck atm_ar_1bp4okc__7pk1ck atm_fc_1h6ojuz__7pk1ck dir dir-ltr&quot;]/div[@class=&quot;d1hw4v9n atm_e2_1osqo2v atm_j6_1665v6k dir dir-ltr&quot;]/div[@class=&quot;_g2s11rv&quot;]/div[1]/div[1]/div[@class=&quot;_14676s3&quot;]/div[@class=&quot;_1foj6yps&quot;]/div[@class=&quot;_2hyui6e&quot;]/div[@class=&quot;_1lds9wb&quot;]/div[@class=&quot;_ytfarf&quot;]/table[@class=&quot;_cvkwaj&quot;]/tbody[1]/tr[2]/td[@class=&quot;cg1lmd0 atm_73_usvi9m atm_9j_tlke0l atm_r3_1h6ojuz atm_mk_h2mmj6 atm_kd_idpfg4_csw3t1 d1ahkqj3 atm_26_1p8m8iw atm_3f_idpfg4 atm_7l_dezgoh atm_l8_idpfg4 atm_kd_glywfm atm_3f_glywfm_jo46a5 atm_l8_idpfg4_jo46a5 atm_gi_idpfg4_jo46a5 atm_3f_glywfm_1icshfk atm_kd_glywfm_19774hq atm_uc_aaiy6o_1w3cfyq atm_wq_kb7nvz_1w3cfyq atm_5j_1osqo2v_1w3cfyq atm_70_plng71_1w3cfyq atm_uc_glywfm_1w3cfyq_1rrf6b5 atm_uc_aaiy6o_pfnrn2_1oszvuo atm_wq_kb7nvz_pfnrn2_1oszvuo atm_5j_1osqo2v_pfnrn2_1oszvuo atm_70_plng71_pfnrn2_1oszvuo atm_uc_glywfm_pfnrn2_1o31aam dir dir-ltr&quot;]/div[@class=&quot;p58w9eu atm_9s_1bgihbq dir dir-ltr&quot;]/div[@class=&quot;c1i3jwjb atm_gz_t94yts atm_h0_t94yts c1buxrsh atm_c8_km0zk7 atm_g3_18khvle atm_fr_1m9t47k atm_9s_1txwivl atm_h_1h6ojuz atm_fc_1h6ojuz atm_ar_1bp4okc atm_5j_1osqo2v atm_mk_h2mmj6 atm_cs_10d11i2 d1qdcyln atm_7l_dezgoh atm_3f_nneixv n1h9hfmv atm_26_1p8m8iw_1nos8r atm_3f_1vpejwz_1nos8r dir dir-ltr notranslate&quot;]</value>
      <webElementGuid>4cf80045-b462-4caf-9ba5-87c15fb097ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel--tabs--0']/div/div/div/div/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[2]/td[6]/div/div</value>
      <webElementGuid>dd756e34-c77c-41e5-85df-8e1f7f2c9ee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='August 2024'])[1]/following::div[18]</value>
      <webElementGuid>0c352802-8eb8-49ed-bf6f-3d6d3f4f155e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='July 2024'])[1]/following::div[83]</value>
      <webElementGuid>3400eae9-c4a0-47b8-b97a-ec5851b3b46d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='September 2024'])[1]/preceding::div[45]</value>
      <webElementGuid>f1d91f84-432e-4dcc-a2b1-fdea8d25e2b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='October 2024'])[1]/preceding::div[108]</value>
      <webElementGuid>80036b18-409e-4960-94e2-734838a62a64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/tbody/tr[2]/td[6]/div/div</value>
      <webElementGuid>4420d954-fede-4c81-841c-50be5afd4677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '9' or . = '9')]</value>
      <webElementGuid>5ba409ee-7de8-4d7b-ad92-d0ef13bf3760</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
